### ISSUE TITLE
document PR requirements

### ISSUE THREAD

**Issue by kevinushey** [rstudio/hex-stickers#23]
Ideally in `README.md`.

- Dimensions for PNG graphics?
- Requirements for SVG graphics (in particular, convert fonts to text outlines)?
- Document best practice for generating PNG from SVG?
- Should we update `meta.json`?

**Comment by hadley** [comment]
Possibly generate PNG from with https://cran.r-project.org/web/packages/rsvg/index.html

**Comment by hadley** [comment]
I did a pass with rsvg and it doesn't do a very good job on the stickers like purrr.
