### ISSUE TITLE
Parnsip svg hex sizing

### ISSUE THREAD

**Issue by apreshill** [rstudio/hex-stickers#26]
In trying to use svg versions of the hex stickers for tidymodels.org (https://github.com/tidymodels/tidymodels.org/pull/161), I see this:

https://deploy-preview-161--tidymodels-org.netlify.app/

<img width="1332" alt="Screen Shot 2020-05-13 at 1 49 23 PM" src="https://user-images.githubusercontent.com/12160301/81863774-933d9480-9520-11ea-8771-2c8b34008b7c.png">

**Comment by gregswinehart** [comment]
Thanks for the heads up, it's fixed!
