### ISSUE TITLE
Tidymodels png hex font is missing

### ISSUE THREAD

**Issue by apreshill** [rstudio/hex-stickers#27]
This was corrected before we launched tidymodels.org:

![](https://www.tidyverse.org/blog/2020/04/tidymodels-org/tidymodels-front-page.png)

But a recent change (perhaps the resizing?) brought the old font back:

<img width="1332" alt="Screen Shot 2020-05-13 at 1 51 19 PM" src="https://user-images.githubusercontent.com/12160301/81864119-06470b00-9521-11ea-9187-3ecdc09ab1f4.png">

thanks to @dcossyleon for noticing!

**Comment by gregswinehart** [comment]
all set!
