### ISSUE TITLE
Contributing newer stickers to hexbin?

### ISSUE THREAD

**Issue by pkq** [rstudio/hex-stickers#4]
Thanks for sharing these! Would you be opposed to me creating a [hexbin](https://github.com/maxogden/hexbin) PR for the newer stickers that aren't there yet?

**Comment by hadley** [comment]
No, that'd be great!

**Comment by hadley** [comment]
I think we can just give up on hexbin for now. I don't think it's that important, and it create a small but persistence maintenance job.
