### ISSUE TITLE
URL location

### ISSUE THREAD

**Issue by schloerke** [rstudio/hex-stickers#43]
Should hexes require a url?

If included, where should it point to? 
* `rstudio.com`
* `www.rstudio.com`
* The package's GitHub site? 
  * Ex: `rstudio.github.io/reactlog` seems very error prone / long
  * Should all R package GitHub sites get CNAME like how `gt` did? `gt.rstudio.com` which is really rstudio.github.io/gt

cc @allisonhorst

**Comment by hadley** [comment]
Generally, I think it should only be to a top level property if it exists (e.g. rstudio.com, tidyverse.org)

**Comment by schloerke** [comment]
Cool. `rplumber.io` will work great.

------------------

If we're doing minimal urls, should hexes like `shiny` point to `shiny.rstudio.com` (currently `www.rstudio.com`) or `dplyr` point to `dplyr.tidyverse.org` (current url).  

Or should they point to `rstudio.com` or `tidyverse.org` respectively?

**Comment by hadley** [comment]
I don't think we really need to have a policy on this; I think you can use whatever you want, but shorter is better.

**Comment by schloerke** [comment]
Closing. Thank you!
