### ISSUE TITLE
Sticker text as curves?

### ISSUE THREAD

**Issue by rensa** [rstudio/hex-stickers#5]
Would you consider offering the SVG version of the stickers with the text rendered as curves? The stickers use a variety of fonts, and they're not always available to users. For example, some stickers use the Myriad Pro font, which most people can only access with a Creative Cloud or TypeKit subscription.

**Comment by rensa** [comment]
For example:

![image](https://user-images.githubusercontent.com/6520659/44944613-4fbef780-ae1d-11e8-93f6-626d2fc0c2b2.png)

**Comment by hadley** [comment]
This should now be fixed I think
