### ISSUE TITLE
there is no Hex sticker for RNotebook?

### ISSUE THREAD

**Issue by elson-faal** [rstudio/hex-stickers#63]
![rnotebook](https://user-images.githubusercontent.com/70442199/135704386-f069960e-745c-47de-89df-13dc039b2cb4.png)

There is no Hex sticker for RNotebook?

I created one to illustrate an article on my blog. From a very simple approach, based on the R Notebook icon in Rstudio.

any chance of being used?

**Comment by hadley** [comment]
RNotebook isn't a package, so it's not something we'd generally give a logo to. I like what you came up with though!
