### ISSUE TITLE
rendering README in GHA on PR when comes from a fork does not work

### ISSUE THREAD

**Issue by cderv** [rstudio/hex-stickers#65]
We encountered this here https://github.com/rstudio/hex-stickers/pull/60 and https://github.com/rstudio/hex-stickers/pull/61. (logs are probably not there anymore). 

In both cases, it came from a fork. The issue is related to the use of `r-lib/actions/pr-push` 
https://github.com/rstudio/hex-stickers/blob/93361e262a3dcdc3913777d9fc36cb503d231a2d/.github/workflows/render-readme.yaml#L31-L33
which doesn't have the correct access right because Github token passed is read-only on fork when trigger on pull request (which is different from comment). 

More on GITHUB_TOKEN permission: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

`pr-push` action was made for comment triggered action in the first place, and write access is there. 

We need a two way process to render the README on PR from fork I guess.

**Comment by hadley** [comment]
Thanks for looking into this!

**Comment by cderv** [comment]
It needs to be triggered only when `/render` is present. Currently it works for any comments. 
I need to fix this

**Comment by cderv** [comment]
Learnt the hard way that in GHA `'' == false` is `true`. So testing is false or missing is the same. Using `contains()` will handle that I believe.

**Comment by cderv** [comment]
And we'll only run the first check on PR.

**Comment by cderv** [comment]
And we'll only run the first step on PR

**Comment by cderv** [comment]
Just testing that this does not trigger a render of the README through `issue_comment` trigger
