### ISSUE TITLE
quarto hex sticker

### ISSUE THREAD

**Issue by persona-ejemplo** [rstudio/hex-stickers#77]
Could you please upload the Quarto hex sticker to this repo? It will make many people happy :sparkles:

**Comment by tracykteal** [comment]
Yes, we can get it up soon! Tagging in @gregswinehart.

**Comment by gregswinehart** [comment]
@persona-ejemplo and @tracykteal, Quarto has been added!

https://github.com/rstudio/hex-stickers/blob/master/PNG/quarto.png
https://github.com/rstudio/hex-stickers/blob/master/SVG/quarto.svg

**Comment by tracykteal** [comment]
Thank you @gregswinehart!
