### ISSUE TITLE
Add "Master of the tidyverse" sticker

### ISSUE THREAD

**Issue by burgerga** [rstudio/hex-stickers#9]
Would love the master of the tidyverse sticker to be uploaded here as well:

![](https://ih1.redbubble.net/image.543343293.1689/bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8.jpg)

(Image linked from [redbubble](https://www.redbubble.com/people/rstudio-inc/works/31171689-master-the-tidyverse-hex-logo?cat_context=all-departments&grid_pos=6&p=sticker&rbs=78472894-0926-4683-8e05-c1bb1f015110&ref=shop_grid&searchTerm=tidyverse))

**Comment by EconomiCurtis** [comment]
I think Hadley and the tidyverse team would prefer to keep this super limited addition, and handed out in person at tidyverse dev days and workshops.

**Comment by burgerga** [comment]
Ha, the value of my old laptop with this sticker on it just went up :P
I'm teaching a course that relies heavily on the tidyverse (and R4DS) so I wanted to include it on the last slide, but I can see the appeal of keeping it limited.

**Comment by hadley** [comment]
Yeah sorry, this is strictly limited edition
